export { default as Title } from './title/Title'
export { default as Heading } from './heading/Heading'
export { Text } from 'rebass'
export { default as Link } from './link/Link'
export { default as Spinner } from './spinner/Spinner'
export { default as HeroIcon } from './heroes/HeroIcon'
